name: Docker Image CI

on:
  schedule:
  - cron: "58 3 * * *"
#   push:
#     branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:v1
    - name: running image
      run: docker run -e phone=${{secrets.PHONE}} -e passwd=${{secrets.PASSWORD}} my-image-name:v1
